---

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install base packages
  apt: name={{ item }} state=installed
  with_items:
    - nginx
    - emacs
    - git
    - python-pip
    - python-dev
    - build-essential
    - supervisor
  tags: packages

- name: Latest version of pip
  pip: name=pip state=latest
  tags: packages

- name: Latest version of virtualenv
  pip: name=virtualenv state=latest
  tags: packages
